// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email_proto.proto

package amq7.samples.protobuf;

public final class EmailProto {
  private EmailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:amq7.samples.protobuf.Email)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string body = 1;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 1;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>string to = 2;</code>
     */
    java.lang.String getTo();
    /**
     * <code>string to = 2;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string subject = 3;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>string subject = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <code>string cc = 6;</code>
     */
    java.lang.String getCc();
    /**
     * <code>string cc = 6;</code>
     */
    com.google.protobuf.ByteString
        getCcBytes();

    /**
     * <code>string cco = 5;</code>
     */
    java.lang.String getCco();
    /**
     * <code>string cco = 5;</code>
     */
    com.google.protobuf.ByteString
        getCcoBytes();
  }
  /**
   * Protobuf type {@code amq7.samples.protobuf.Email}
   */
  public  static final class Email extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:amq7.samples.protobuf.Email)
      EmailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Email.newBuilder() to construct.
    private Email(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Email() {
      body_ = "";
      to_ = "";
      subject_ = "";
      cc_ = "";
      cco_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Email(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (dateTime_ != null) {
                subBuilder = dateTime_.toBuilder();
              }
              dateTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dateTime_);
                dateTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cco_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              cc_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return amq7.samples.protobuf.EmailProto.internal_static_amq7_samples_protobuf_Email_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return amq7.samples.protobuf.EmailProto.internal_static_amq7_samples_protobuf_Email_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              amq7.samples.protobuf.EmailProto.Email.class, amq7.samples.protobuf.EmailProto.Email.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 1;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object to_;
    /**
     * <code>string to = 2;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object subject_;
    /**
     * <code>string subject = 3;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <code>string subject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    public boolean hasDateTime() {
      return dateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return getDateTime();
    }

    public static final int CC_FIELD_NUMBER = 6;
    private volatile java.lang.Object cc_;
    /**
     * <code>string cc = 6;</code>
     */
    public java.lang.String getCc() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cc_ = s;
        return s;
      }
    }
    /**
     * <code>string cc = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCcBytes() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CCO_FIELD_NUMBER = 5;
    private volatile java.lang.Object cco_;
    /**
     * <code>string cco = 5;</code>
     */
    public java.lang.String getCco() {
      java.lang.Object ref = cco_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cco_ = s;
        return s;
      }
    }
    /**
     * <code>string cco = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCcoBytes() {
      java.lang.Object ref = cco_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cco_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, body_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subject_);
      }
      if (dateTime_ != null) {
        output.writeMessage(4, getDateTime());
      }
      if (!getCcoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cco_);
      }
      if (!getCcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, body_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subject_);
      }
      if (dateTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDateTime());
      }
      if (!getCcoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cco_);
      }
      if (!getCcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof amq7.samples.protobuf.EmailProto.Email)) {
        return super.equals(obj);
      }
      amq7.samples.protobuf.EmailProto.Email other = (amq7.samples.protobuf.EmailProto.Email) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      result = result && getTo()
          .equals(other.getTo());
      result = result && getSubject()
          .equals(other.getSubject());
      result = result && (hasDateTime() == other.hasDateTime());
      if (hasDateTime()) {
        result = result && getDateTime()
            .equals(other.getDateTime());
      }
      result = result && getCc()
          .equals(other.getCc());
      result = result && getCco()
          .equals(other.getCco());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      if (hasDateTime()) {
        hash = (37 * hash) + DATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getDateTime().hashCode();
      }
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + getCc().hashCode();
      hash = (37 * hash) + CCO_FIELD_NUMBER;
      hash = (53 * hash) + getCco().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static amq7.samples.protobuf.EmailProto.Email parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(amq7.samples.protobuf.EmailProto.Email prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code amq7.samples.protobuf.Email}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:amq7.samples.protobuf.Email)
        amq7.samples.protobuf.EmailProto.EmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return amq7.samples.protobuf.EmailProto.internal_static_amq7_samples_protobuf_Email_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return amq7.samples.protobuf.EmailProto.internal_static_amq7_samples_protobuf_Email_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                amq7.samples.protobuf.EmailProto.Email.class, amq7.samples.protobuf.EmailProto.Email.Builder.class);
      }

      // Construct using amq7.samples.protobuf.EmailProto.Email.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        body_ = "";

        to_ = "";

        subject_ = "";

        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }
        cc_ = "";

        cco_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return amq7.samples.protobuf.EmailProto.internal_static_amq7_samples_protobuf_Email_descriptor;
      }

      @java.lang.Override
      public amq7.samples.protobuf.EmailProto.Email getDefaultInstanceForType() {
        return amq7.samples.protobuf.EmailProto.Email.getDefaultInstance();
      }

      @java.lang.Override
      public amq7.samples.protobuf.EmailProto.Email build() {
        amq7.samples.protobuf.EmailProto.Email result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public amq7.samples.protobuf.EmailProto.Email buildPartial() {
        amq7.samples.protobuf.EmailProto.Email result = new amq7.samples.protobuf.EmailProto.Email(this);
        result.body_ = body_;
        result.to_ = to_;
        result.subject_ = subject_;
        if (dateTimeBuilder_ == null) {
          result.dateTime_ = dateTime_;
        } else {
          result.dateTime_ = dateTimeBuilder_.build();
        }
        result.cc_ = cc_;
        result.cco_ = cco_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof amq7.samples.protobuf.EmailProto.Email) {
          return mergeFrom((amq7.samples.protobuf.EmailProto.Email)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(amq7.samples.protobuf.EmailProto.Email other) {
        if (other == amq7.samples.protobuf.EmailProto.Email.getDefaultInstance()) return this;
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (other.hasDateTime()) {
          mergeDateTime(other.getDateTime());
        }
        if (!other.getCc().isEmpty()) {
          cc_ = other.cc_;
          onChanged();
        }
        if (!other.getCco().isEmpty()) {
          cco_ = other.cco_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        amq7.samples.protobuf.EmailProto.Email parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (amq7.samples.protobuf.EmailProto.Email) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 1;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 1;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 2;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <code>string subject = 3;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public boolean hasDateTime() {
        return dateTimeBuilder_ != null || dateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (dateTime_ != null) {
            dateTime_ =
              com.google.protobuf.Timestamp.newBuilder(dateTime_).mergeFrom(value).buildPartial();
          } else {
            dateTime_ = value;
          }
          onChanged();
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
          onChanged();
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private java.lang.Object cc_ = "";
      /**
       * <code>string cc = 6;</code>
       */
      public java.lang.String getCc() {
        java.lang.Object ref = cc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cc = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCcBytes() {
        java.lang.Object ref = cc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cc = 6;</code>
       */
      public Builder setCc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 6;</code>
       */
      public Builder clearCc() {
        
        cc_ = getDefaultInstance().getCc();
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 6;</code>
       */
      public Builder setCcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cco_ = "";
      /**
       * <code>string cco = 5;</code>
       */
      public java.lang.String getCco() {
        java.lang.Object ref = cco_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cco_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cco = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCcoBytes() {
        java.lang.Object ref = cco_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cco_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cco = 5;</code>
       */
      public Builder setCco(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cco_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cco = 5;</code>
       */
      public Builder clearCco() {
        
        cco_ = getDefaultInstance().getCco();
        onChanged();
        return this;
      }
      /**
       * <code>string cco = 5;</code>
       */
      public Builder setCcoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cco_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:amq7.samples.protobuf.Email)
    }

    // @@protoc_insertion_point(class_scope:amq7.samples.protobuf.Email)
    private static final amq7.samples.protobuf.EmailProto.Email DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new amq7.samples.protobuf.EmailProto.Email();
    }

    public static amq7.samples.protobuf.EmailProto.Email getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Email>
        PARSER = new com.google.protobuf.AbstractParser<Email>() {
      @java.lang.Override
      public Email parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Email(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Email> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Email> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public amq7.samples.protobuf.EmailProto.Email getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amq7_samples_protobuf_Email_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amq7_samples_protobuf_Email_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021email_proto.proto\022\025amq7.samples.protob" +
      "uf\032\037google/protobuf/timestamp.proto\"y\n\005E" +
      "mail\022\014\n\004body\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007subjec" +
      "t\030\003 \001(\t\022,\n\010dateTime\030\004 \001(\0132\032.google.proto" +
      "buf.Timestamp\022\n\n\002cc\030\006 \001(\t\022\013\n\003cco\030\005 \001(\tB\027" +
      "\n\025amq7.samples.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_amq7_samples_protobuf_Email_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amq7_samples_protobuf_Email_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amq7_samples_protobuf_Email_descriptor,
        new java.lang.String[] { "Body", "To", "Subject", "DateTime", "Cc", "Cco", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
